In [8]:
import pandas as pd

In [9]:
df_train = pd.read_csv("/data/churn-bigml-80.csv")
df_train.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [10]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2666 entries, 0 to 2665
Data columns (total 20 columns):
State                     2666 non-null object
Account length            2666 non-null int64
Area code                 2666 non-null int64
International plan        2666 non-null object
Voice mail plan           2666 non-null object
Number vmail messages     2666 non-null int64
Total day minutes         2666 non-null float64
Total day calls           2666 non-null int64
Total day charge          2666 non-null float64
Total eve minutes         2666 non-null float64
Total eve calls           2666 non-null int64
Total eve charge          2666 non-null float64
Total night minutes       2666 non-null float64
Total night calls         2666 non-null int64
Total night charge        2666 non-null float64
Total intl minutes        2666 non-null float64
Total intl calls          2666 non-null int64
Total intl charge         2666 non-null float64
Customer service calls    2666 non-null int64
Churn                     2666 non-null bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 398.4+ KB

In [16]:
df_train.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [62]:
df_train.Churn.value_counts()/len(df_train)

False    0.854464
True     0.145536
Name: Churn, dtype: float64

In [52]:
df_test = pd.read_csv("/data/churn-bigml-20.csv")
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 20 columns):
State                     667 non-null object
Account length            667 non-null int64
Area code                 667 non-null int64
International plan        667 non-null object
Voice mail plan           667 non-null object
Number vmail messages     667 non-null int64
Total day minutes         667 non-null float64
Total day calls           667 non-null int64
Total day charge          667 non-null float64
Total eve minutes         667 non-null float64
Total eve calls           667 non-null int64
Total eve charge          667 non-null float64
Total night minutes       667 non-null float64
Total night calls         667 non-null int64
Total night charge        667 non-null float64
Total intl minutes        667 non-null float64
Total intl calls          667 non-null int64
Total intl charge         667 non-null float64
Customer service calls    667 non-null int64
Churn                     667 non-null bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 99.7+ KB

In [53]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [54]:
df = pd.concat([df_train, df_test])
df.shape

(3333, 20)

In [55]:
df.pivot_table("Account length", index="Churn",columns=["Customer service calls"], aggfunc="count", margins=True)

Customer service calls,0,1,2,3,4,5,6,7,8,9,All
Churn,,,,,,,,,,,
False,605.0,1059.0,672.0,385.0,90.0,26.0,8.0,4.0,1.0,NaN,2850
True,92.0,122.0,87.0,44.0,76.0,40.0,14.0,5.0,1.0,2.0,483
All,697.0,1181.0,759.0,429.0,166.0,66.0,22.0,9.0,2.0,2.0,3333

In [69]:
df_dummy = pd.get_dummies(df.drop(columns="Churn"), columns=["State", "Area code", "International plan",
                                                             "Voice mail plan"])
df_dummy.shape

(3333, 73)

In [60]:
df_dummy.head()

,Account length,International plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,...,State_VT,State_WA,State_WI,State_WV,State_WY,Area code_408,Area code_415,Area code_510,Voice mail plan_No,Voice mail plan_Yes
0,128,No,25,265.1,110,45.07,197.4,99,16.78,244.7,...,0,0,0,0,0,0,1,0,0,1
1,107,No,26,161.6,123,27.47,195.5,103,16.62,254.4,...,0,0,0,0,0,0,1,0,0,1
2,137,No,0,243.4,114,41.38,121.2,110,10.30,162.6,...,0,0,0,0,0,0,1,0,1,0
3,84,Yes,0,299.4,71,50.90,61.9,88,5.26,196.9,...,0,0,0,0,0,1,0,0,1,0
4,75,Yes,0,166.7,113,28.34,148.3,122,12.61,186.9,...,0,0,0,0,0,0,1,0,1,0

In [71]:
from sklearn import preprocessing
from sklearn import pipeline

In [77]:
scaler = preprocessing.StandardScaler()

X_train = df_dummy.iloc[:len(df_train),:].values
X_test = df_dummy.iloc[len(df_train):,:].values

X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)


label_encoder = preprocessing.LabelEncoder()
y_train = label_encoder.fit_transform(df_train.Churn)
y_test = label_encoder.transform(df_test.Churn)

In [129]:
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn import metrics

In [150]:
cls = SGDClassifier(loss="log", random_state=1, max_iter=2000, l1_ratio=0.1, learning_rate="invscaling", eta0=0.001)
cls.fit(X_train_std, y_train)
cls.score(X_test_std, y_test)
print("Accuracy", est.score(X_test_std, y_test))
metrics.confusion_matrix(y_test, est.predict(X_test_std))

Accuracy 0.856071964017991

array([[571,   1],
       [ 95,   0]])

In [153]:
est = LogisticRegression()
est.fit(X_train_std, y_train)
print("Accuracy", est.score(X_test_std, y_test))
metrics.confusion_matrix(y_test, est.predict(X_test_std))

Accuracy 0.8590704647676162

array([[549,  23],
       [ 71,  24]])

In [154]:
from sklearn.tree import DecisionTreeClassifier
est = DecisionTreeClassifier(max_depth=5, random_state=1)
est.fit(X_train, y_train)
print("Accuracy", est.score(X_test, y_test))
metrics.confusion_matrix(y_test, est.predict(X_test))

Accuracy 0.9505247376311844

array([[558,  14],
       [ 19,  76]])

In [164]:
from sklearn.ensemble import RandomForestClassifier
est = RandomForestClassifier(max_depth=5, random_state=1)
est.fit(X_train, y_train)
est.score(X_test, y_test)
print("Accuracy", est.score(X_test, y_test))
metrics.confusion_matrix(y_test, est.predict(X_test))

Accuracy 0.8695652173913043

array([[570,   2],
       [ 85,  10]])

In [109]:
import keras

Using TensorFlow backend.

In [163]:
adam = keras.optimizers.Adam(lr=0.01)

model = keras.Sequential()
model.add(keras.layers.InputLayer(input_shape = (X_train_std.shape[1],)))
model.add(keras.layers.Dropout(0.1))
model.add(keras.layers.Dense(1, activation="sigmoid"))

model.compile(adam, "binary_crossentropy", ["acc"])

model.fit(X_train_std, y_train, validation_data=(X_test_std, y_test), epochs=100)

Train on 2666 samples, validate on 667 samples
Epoch 1/100
2666/2666 [==============================] - 1s 243us/step - loss: 0.6074 - acc: 0.7082 - val_loss: 0.4509 - val_acc: 0.8411
Epoch 2/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.4130 - acc: 0.8473 - val_loss: 0.3734 - val_acc: 0.8486
Epoch 3/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3591 - acc: 0.8620 - val_loss: 0.3454 - val_acc: 0.8621
Epoch 4/100
2666/2666 [==============================] - 0s 28us/step - loss: 0.3497 - acc: 0.8582 - val_loss: 0.3417 - val_acc: 0.8531
Epoch 5/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3376 - acc: 0.8657 - val_loss: 0.3353 - val_acc: 0.8606
Epoch 6/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3350 - acc: 0.8616 - val_loss: 0.3366 - val_acc: 0.8651
Epoch 7/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3334 - acc: 0.8635 - val_loss: 0.3358 - val_acc: 0.8621
Epoch 8/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3355 - acc: 0.8668 - val_loss: 0.3349 - val_acc: 0.8621
Epoch 9/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3315 - acc: 0.8627 - val_loss: 0.3330 - val_acc: 0.8546
Epoch 10/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3304 - acc: 0.8668 - val_loss: 0.3369 - val_acc: 0.8576
Epoch 11/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3305 - acc: 0.8642 - val_loss: 0.3310 - val_acc: 0.8591
Epoch 12/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3368 - acc: 0.8638 - val_loss: 0.3277 - val_acc: 0.8591
Epoch 13/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3347 - acc: 0.8605 - val_loss: 0.3364 - val_acc: 0.8546
Epoch 14/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3301 - acc: 0.8638 - val_loss: 0.3351 - val_acc: 0.8636
Epoch 15/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3309 - acc: 0.8661 - val_loss: 0.3327 - val_acc: 0.8666
Epoch 16/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3308 - acc: 0.8638 - val_loss: 0.3335 - val_acc: 0.8621
Epoch 17/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3335 - acc: 0.8687 - val_loss: 0.3375 - val_acc: 0.8561
Epoch 18/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3359 - acc: 0.8601 - val_loss: 0.3371 - val_acc: 0.8531
Epoch 19/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3266 - acc: 0.8672 - val_loss: 0.3393 - val_acc: 0.8471
Epoch 20/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3319 - acc: 0.8635 - val_loss: 0.3357 - val_acc: 0.8546
Epoch 21/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3307 - acc: 0.8680 - val_loss: 0.3339 - val_acc: 0.8576
Epoch 22/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3312 - acc: 0.8653 - val_loss: 0.3370 - val_acc: 0.8621
Epoch 23/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3336 - acc: 0.8608 - val_loss: 0.3348 - val_acc: 0.8591
Epoch 24/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3272 - acc: 0.8683 - val_loss: 0.3341 - val_acc: 0.8576
Epoch 25/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3358 - acc: 0.8638 - val_loss: 0.3340 - val_acc: 0.8576
Epoch 26/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3323 - acc: 0.8635 - val_loss: 0.3382 - val_acc: 0.8606
Epoch 27/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3382 - acc: 0.8582 - val_loss: 0.3324 - val_acc: 0.8546
Epoch 28/100
2666/2666 [==============================] - 0s 34us/step - loss: 0.3394 - acc: 0.8638 - val_loss: 0.3302 - val_acc: 0.8561
Epoch 29/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3338 - acc: 0.8657 - val_loss: 0.3395 - val_acc: 0.8621
Epoch 30/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3359 - acc: 0.8642 - val_loss: 0.3411 - val_acc: 0.8531
Epoch 31/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3316 - acc: 0.8683 - val_loss: 0.3405 - val_acc: 0.8561
Epoch 32/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3352 - acc: 0.8635 - val_loss: 0.3355 - val_acc: 0.8606
Epoch 33/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3365 - acc: 0.8631 - val_loss: 0.3286 - val_acc: 0.8531
Epoch 34/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3297 - acc: 0.8638 - val_loss: 0.3341 - val_acc: 0.8546
Epoch 35/100
2666/2666 [==============================] - 0s 34us/step - loss: 0.3314 - acc: 0.8642 - val_loss: 0.3296 - val_acc: 0.8606
Epoch 36/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3338 - acc: 0.8646 - val_loss: 0.3327 - val_acc: 0.8636
Epoch 37/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3296 - acc: 0.8687 - val_loss: 0.3336 - val_acc: 0.8606
Epoch 38/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3363 - acc: 0.8635 - val_loss: 0.3399 - val_acc: 0.8546
Epoch 39/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3307 - acc: 0.8642 - val_loss: 0.3314 - val_acc: 0.8576
Epoch 40/100
2666/2666 [==============================] - 0s 28us/step - loss: 0.3314 - acc: 0.8638 - val_loss: 0.3360 - val_acc: 0.8486
Epoch 41/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3349 - acc: 0.8653 - val_loss: 0.3435 - val_acc: 0.8576
Epoch 42/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3328 - acc: 0.8635 - val_loss: 0.3343 - val_acc: 0.8621
Epoch 43/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3324 - acc: 0.8661 - val_loss: 0.3369 - val_acc: 0.8591
Epoch 44/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3338 - acc: 0.8620 - val_loss: 0.3383 - val_acc: 0.8576
Epoch 45/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3343 - acc: 0.8646 - val_loss: 0.3344 - val_acc: 0.8501
Epoch 46/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3335 - acc: 0.8646 - val_loss: 0.3398 - val_acc: 0.8561
Epoch 47/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3305 - acc: 0.8653 - val_loss: 0.3371 - val_acc: 0.8606
Epoch 48/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3346 - acc: 0.8657 - val_loss: 0.3336 - val_acc: 0.8621
Epoch 49/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3307 - acc: 0.8653 - val_loss: 0.3369 - val_acc: 0.8576
Epoch 50/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3371 - acc: 0.8642 - val_loss: 0.3376 - val_acc: 0.8591
Epoch 51/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3316 - acc: 0.8657 - val_loss: 0.3367 - val_acc: 0.8606
Epoch 52/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3327 - acc: 0.8642 - val_loss: 0.3408 - val_acc: 0.8606
Epoch 53/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3352 - acc: 0.8657 - val_loss: 0.3373 - val_acc: 0.8561
Epoch 54/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3364 - acc: 0.8612 - val_loss: 0.3341 - val_acc: 0.8606
Epoch 55/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3359 - acc: 0.8623 - val_loss: 0.3322 - val_acc: 0.8606
Epoch 56/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3343 - acc: 0.8657 - val_loss: 0.3291 - val_acc: 0.8591
Epoch 57/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3294 - acc: 0.8627 - val_loss: 0.3349 - val_acc: 0.8606
Epoch 58/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3351 - acc: 0.8627 - val_loss: 0.3400 - val_acc: 0.8546
Epoch 59/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3341 - acc: 0.8665 - val_loss: 0.3370 - val_acc: 0.8606
Epoch 60/100

2666/2666 [==============================] - 0s 30us/step - loss: 0.3378 - acc: 0.8657 - val_loss: 0.3367 - val_acc: 0.8561
Epoch 61/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3337 - acc: 0.8661 - val_loss: 0.3354 - val_acc: 0.8576
Epoch 62/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3326 - acc: 0.8653 - val_loss: 0.3352 - val_acc: 0.8591
Epoch 63/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3284 - acc: 0.8631 - val_loss: 0.3327 - val_acc: 0.8591
Epoch 64/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3283 - acc: 0.8698 - val_loss: 0.3354 - val_acc: 0.8591
Epoch 65/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3304 - acc: 0.8687 - val_loss: 0.3397 - val_acc: 0.8546
Epoch 66/100
2666/2666 [==============================] - 0s 28us/step - loss: 0.3387 - acc: 0.8605 - val_loss: 0.3339 - val_acc: 0.8576
Epoch 67/100
2666/2666 [==============================] - 0s 27us/step - loss: 0.3300 - acc: 0.8691 - val_loss: 0.3310 - val_acc: 0.8561
Epoch 68/100
2666/2666 [==============================] - 0s 28us/step - loss: 0.3352 - acc: 0.8650 - val_loss: 0.3390 - val_acc: 0.8501
Epoch 69/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3284 - acc: 0.8657 - val_loss: 0.3345 - val_acc: 0.8516
Epoch 70/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3366 - acc: 0.8608 - val_loss: 0.3349 - val_acc: 0.8621
Epoch 71/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3288 - acc: 0.8635 - val_loss: 0.3326 - val_acc: 0.8561
Epoch 72/100
2666/2666 [==============================] - 0s 28us/step - loss: 0.3368 - acc: 0.8650 - val_loss: 0.3377 - val_acc: 0.8561
Epoch 73/100
2666/2666 [==============================] - 0s 28us/step - loss: 0.3302 - acc: 0.8653 - val_loss: 0.3327 - val_acc: 0.8606
Epoch 74/100
2666/2666 [==============================] - 0s 27us/step - loss: 0.3335 - acc: 0.8650 - val_loss: 0.3380 - val_acc: 0.8666
Epoch 75/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3389 - acc: 0.8668 - val_loss: 0.3346 - val_acc: 0.8576
Epoch 76/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3329 - acc: 0.8646 - val_loss: 0.3316 - val_acc: 0.8591
Epoch 77/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3343 - acc: 0.8650 - val_loss: 0.3411 - val_acc: 0.8546
Epoch 78/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3328 - acc: 0.8657 - val_loss: 0.3313 - val_acc: 0.8606
Epoch 79/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3264 - acc: 0.8702 - val_loss: 0.3368 - val_acc: 0.8561
Epoch 80/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3346 - acc: 0.8668 - val_loss: 0.3376 - val_acc: 0.8546
Epoch 81/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3293 - acc: 0.8657 - val_loss: 0.3334 - val_acc: 0.8591
Epoch 82/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3276 - acc: 0.8616 - val_loss: 0.3342 - val_acc: 0.8591
Epoch 83/100
2666/2666 [==============================] - 0s 35us/step - loss: 0.3326 - acc: 0.8646 - val_loss: 0.3338 - val_acc: 0.8636
Epoch 84/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3270 - acc: 0.8695 - val_loss: 0.3296 - val_acc: 0.8636
Epoch 85/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3325 - acc: 0.8627 - val_loss: 0.3351 - val_acc: 0.8621
Epoch 86/100
2666/2666 [==============================] - 0s 34us/step - loss: 0.3319 - acc: 0.8627 - val_loss: 0.3378 - val_acc: 0.8651
Epoch 87/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3381 - acc: 0.8642 - val_loss: 0.3370 - val_acc: 0.8621
Epoch 88/100
2666/2666 [==============================] - 0s 32us/step - loss: 0.3350 - acc: 0.8616 - val_loss: 0.3327 - val_acc: 0.8606
Epoch 89/100
2666/2666 [==============================] - 0s 34us/step - loss: 0.3321 - acc: 0.8608 - val_loss: 0.3338 - val_acc: 0.8681
Epoch 90/100
2666/2666 [==============================] - 0s 41us/step - loss: 0.3368 - acc: 0.8657 - val_loss: 0.3325 - val_acc: 0.8516
Epoch 91/100
2666/2666 [==============================] - 0s 35us/step - loss: 0.3342 - acc: 0.8608 - val_loss: 0.3333 - val_acc: 0.8606
Epoch 92/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3322 - acc: 0.8665 - val_loss: 0.3362 - val_acc: 0.8516
Epoch 93/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3351 - acc: 0.8635 - val_loss: 0.3363 - val_acc: 0.8516
Epoch 94/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3321 - acc: 0.8605 - val_loss: 0.3372 - val_acc: 0.8576
Epoch 95/100
2666/2666 [==============================] - 0s 33us/step - loss: 0.3334 - acc: 0.8646 - val_loss: 0.3356 - val_acc: 0.8546
Epoch 96/100
2666/2666 [==============================] - 0s 29us/step - loss: 0.3368 - acc: 0.8612 - val_loss: 0.3350 - val_acc: 0.8561
Epoch 97/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3377 - acc: 0.8597 - val_loss: 0.3407 - val_acc: 0.8621
Epoch 98/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3307 - acc: 0.8661 - val_loss: 0.3304 - val_acc: 0.8606
Epoch 99/100
2666/2666 [==============================] - 0s 30us/step - loss: 0.3279 - acc: 0.8661 - val_loss: 0.3387 - val_acc: 0.8621
Epoch 100/100
2666/2666 [==============================] - 0s 31us/step - loss: 0.3341 - acc: 0.8635 - val_loss: 0.3344 - val_acc: 0.8561