# Exercise: power demand prediction

Problem description: https://archive.ics.uci.edu/ml/datasets/combined+cycle+power+plant
- Data is provided in two formats - xlsx and ods. Use pd.read_excel to load the data .xlsx file. The excel file has 5 sheets. Create a dataframe for each and concatenate them into a single dataframe. [Hint: use pd.concat function]. Note: one column need to renamed: PE => EP to be consistent with the problem statement.
- Create training and test set with 70/30 ratio and random seed = 1. Predict EP based on the other variables as features (AT, RH, V and AP). 
- Calculate R2 and RMSE for training and test data. [Answer: 0.9287, 0.9284 (r2) 4.55 4.57 (rmse)]
- Find the residuals (ypredict - ytrue) on the test data and plot histogram to see its distribution. Ideally the histogram of the residuals should look "gaussian normal". Do a scatter plot for residual vs actual. Observe whether the residuals are consistently same for entire range of actual. 
- Which features are positively related with the outcome and which are negatively related?
- Which feature is the strongest predictor?
- Improve your model using log transformation of the output and polynomial transformation of the features with degree = 2 [Answer: 0.9371, 0.9369]. Also, plot the residual on the test data.

In [1]:
import pandas as pd

In [3]:
sheets = [pd.read_excel("/Users/abasar/Downloads/CCPP/Folds5x2_pp.xlsx", i) for i in range(5)]

In [6]:
len(sheets)

5

In [8]:
df = pd.concat(sheets)
df.shape

(47840, 5)

In [9]:
df.head()

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [31]:
d = pd.ExcelFile("/Users/abasar/Downloads/CCPP/Folds5x2_pp.xlsx")

In [12]:
d.sheet_names

['Sheet1', 'Sheet2', 'Sheet3', 'Sheet4', 'Sheet5']

In [23]:
sheets = pd.read_excel("/Users/abasar/Downloads/CCPP/Folds5x2_pp.xlsx", sheet_name=None)

In [28]:
pd.concat(sheets).reset_index().iloc[:, 2:]

          AT      V       AP     RH      PE
0      14.96  41.76  1024.07  73.17  463.26
1      25.18  62.96  1020.04  59.08  444.37
2       5.11  39.40  1012.16  92.14  488.56
3      20.86  57.32  1010.24  76.64  446.48
4      10.82  37.50  1009.23  96.62  473.90
5      26.27  59.44  1012.23  58.77  443.67
6      15.89  43.96  1014.02  75.24  467.35
7       9.48  44.71  1019.12  66.43  478.42
8      14.64  45.00  1021.78  41.25  475.98
9      11.74  43.56  1015.14  70.72  477.50
10     17.99  43.72  1008.64  75.04  453.02
11     20.14  46.93  1014.66  64.22  453.99
12     24.34  73.50  1011.31  84.15  440.29
13     25.71  58.59  1012.77  61.83  451.28
14     26.19  69.34  1009.48  87.59  433.99
15     21.42  43.79  1015.76  43.08  462.19
16     18.21  45.00  1022.86  48.84  467.54
17     11.04  41.74  1022.60  77.51  477.20
18     14.45  52.75  1023.97  63.59  459.85
19     13.97  38.47  1015.15  55.28  464.30
20     17.76  42.42  1009.09  66.26  468.27
21      5.41  40.07  1019.16  64.77  495.24
22      7.76  42.28  1008.52  83.31  483.80
23     27.23  63.90  1014.30  47.19  443.61
24     27.36  48.60  1003.18  54.93  436.06
25     27.47  70.72  1009.97  74.62  443.25
26     14.60  39.31  1011.11  72.52  464.16
27      7.91  39.96  1023.57  88.44  475.52
28      5.81  35.79  1012.14  92.28  484.41
29     30.53  65.18  1012.69  41.85  437.89
...      ...    ...      ...    ...     ...
47810   7.11  43.13  1018.96  87.82  486.11
47811  21.54  58.12  1015.33  78.67  454.32
47812  29.45  64.96  1005.52  59.92  433.04
47813  31.85  68.30  1014.76  47.06  428.72
47814  27.30  65.12  1016.24  44.87  442.78
47815  13.51  39.31  1012.18  75.19  466.46
47816  16.73  39.64  1008.94  74.91  464.46
47817  25.45  69.59  1008.51  83.17  445.61
47818  12.88  44.34  1016.03  88.51  474.94
47819  22.29  43.79  1015.68  41.75  461.23
47820  12.07  40.81  1025.63  68.02  475.96
47821  18.21  62.26  1011.97  87.28  455.88
47822  17.53  42.24  1016.90  60.95  470.63
47823  23.66  61.86  1013.33  83.09  444.27
47824  14.18  40.69  1014.73  74.88  471.52
47825  13.85  41.39  1018.62  75.55  471.45
47826  10.06  37.83  1005.49  99.46  473.51
47827  26.89  70.32  1012.39  87.17  435.56
47828   7.72  41.14  1025.11  96.75  478.34
47829  27.06  43.77  1011.02  42.61  442.15
47830  20.18  43.56  1013.14  39.16  462.80
47831  18.51  50.90  1012.95  82.71  459.11
47832  13.60  39.82  1013.34  86.10  470.69
47833  33.42  68.51  1011.91  45.83  427.66
47834  13.79  42.07  1018.27  88.06  462.25
47835  15.12  48.92  1011.80  72.93  462.59
47836  33.41  77.95  1010.30  59.72  432.90
47837  15.99  43.34  1014.20  78.66  465.96
47838  17.65  59.87  1018.58  94.65  450.93
47839  23.68  51.30  1011.86  71.24  451.67

[47840 rows x 5 columns]

In [37]:
d = pd.read_excel("/Users/abasar/Downloads/CCPP/Folds5x2_pp.xlsx", sheet_name=None)

In [39]:
df = pd.concat(d)

In [42]:
df.to_excel("sample.xlsx")

In [44]:
from sklearn import * 
import numpy as np

In [46]:
target = "PE"

y = np.log(df[target])
X = df.drop(columns=[target])

#X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = model_selection.train_test_split(X.values.astype("float")
                                    , y , test_size = 0.3, random_state = 1)


pipe = pipeline.Pipeline([
    ("poly", preprocessing.PolynomialFeatures(degree=1, include_bias=False)),
    ("scaler", preprocessing.StandardScaler()),
    ("est",linear_model.SGDRegressor(random_state=1, eta0=0.001, tol=1e-5
                            , learning_rate="constant"
                            , max_iter= 10000))
])
pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_test_pred = pipe.predict(X_test)

print("r2 train", metrics.r2_score(y_train, y_train_pred))
print("r2 test", metrics.r2_score(y_test, y_test_pred))

print("rmse train", np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print("rmse test", np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))

r2 train 0.9298576765179799
r2 test 0.9293905140170381
rmse train 0.009895690777298703
rmse test 0.009945029405191382